version: "3.4"
services:
  safecoin:
    image: safecoin/safecoin
    depends_on:
      - tor
    ports:
      - "${SAFEPORT:-8770}:8770"
    volumes:
      - safecoin-data:/safecoin
    restart: unless-stopped
    stop_grace_period: 2m
  tor:
    build: ./tor
    volumes:
      - tor-data:/var/lib/tor
    restart: unless-stopped

volumes:
  safecoin-data:
  tor-data: