# From https://gitlab.torproject.org/tpo/anti-censorship/docker-obfs4-bridge/-/commit/a68e0ee731f638e74442119d0c5c9d5ad48b9d3e

version: "3.4"
services:
  obfs4-bridge:
    image: thetorproject/obfs4-bridge:latest
    environment:
      # Exit with an error message if OR_PORT is unset or empty.
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      # Exit with an error message if PT_PORT is unset or empty.
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      # Exit with an error message if EMAIL is unset or empty.
      - EMAIL=${EMAIL:?Env var EMAIL is not set.}
    volumes:
      - obfs4-data:/var/lib/tor
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped
  snowflake-proxy:
    image: thetorproject/snowflake-proxy:latest
    restart: unless-stopped

volumes:
  obfs4-data:
    name: tor-datadir-${OR_PORT}-${PT_PORT}